apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trio-dev
  namespace: codefresh
  labels:
    app: trio-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: trio-dev
    name: in-cluster
  project: trio
  source:
    repoURL: https://github.com/GITHUB_USER/GITHUB_REPO.git
    targetRevision: main
    path: ./k8s-resources/trio/dev
    helm:
      parameters:
        - name: buildID
          value: argocd
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
