apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-dev
  namespace: codefresh
  labels:
    app: express-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: express-dev
    name: CLUSTER_NAME
  project: express
  source:
    path: ./k8s-resources/express/overlays/dev
    repoURL: https://github.com/nightmar39/cd-five-mins.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
